--STORED PROCEDURE
--INSIDE PROGRAMABILITY FOLDER

use DLithe;

--STORED PREOCEDURE
CREATE PROCEDURE PROC_DT2
AS
BEGIN
SELECT * FROM DLITHE_TRAINEES WHERE TID<100;
END

INSERT INTO DLITHE_TRAINEES VALUES(10, 'CHARAN', 1000000,'SHIVAMOGGA','DIT01');
INSERT INTO DLITHE_TRAINEES VALUES(20, 'KIRAN', 7000000,'PUNE','DIT01');
INSERT INTO DLITHE_TRAINEES(TID, TNAME, TADDRESS, TDEPT) VALUES(30, 'VENKATESH','HYDERABHAD','DIT02');
SELECT * FROM DLITHE_TRAINEES;

exec PROC_DT2;


--===========================================================
--ALTER STORED PROCEDURE
ALTER PROCEDURE PROC_DT2
AS
BEGIN
SELECT * FROM DLITHE_TRAINEES WHERE TID<100 AND TADDRESS='PUNE';
END

EXEC PROC_DT2



--====================================================================
--DROP STORED PROCEDURE
DROP PROCEDURE PROC_DT2;




--=====================================================
--SP WITH INPUT PARAMETER

CREATE PROCEDURE PROC_DT(@TADDRESS VARCHAR(50))
AS
BEGIN
SELECT * FROM DLITHE_TRAINEES WHERE TADDRESS=@TADDRESS
END

EXEC PROC_DT @TADDRESS='Pune';


--================================
--SP WITH OUTPUT PARAMETER

CREATE PROCEDURE PROC_DT2(@TID INT OUTPUT)
AS
BEGIN 
SELECT @TID=MAX(TID) FROM DLITHE_TRAINEES
END

DECLARE @TID INT 
EXEC PROC_DT2 @TID OUTPUT
PRINT @TID